### ISSUE TITLE
关于方法的问题？

### ISSUE THREAD

**Issue by cy-biggray** [naecoo/funcwork#5]
1. 上一个issues删了吗？ 找不到了。
2. 问个问题，。就是从主线程传递到work线程的方法，怎么保证不丢失他的作用域？ 现在传递过去的方法是一个空白方法，他本身的作用域已经丢失了。这很难搞

**Comment by naecoo** [comment]
作用域没有办法保留，因为 web worker 环境和主线程是隔离的。我推荐是拆分成不同的纯函数，然后通过参数传递数据。
实在不行，我推荐你使用 [shared worker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker)，`funcwork` 还不支持，你可以看看谷歌的 [Comlink](https://github.com/GoogleChromeLabs/comlink/tree/36d7bfae84f4fcacf2e6d922701dae331eece071/docs/examples/07-sharedworker-example)
